import Head from 'next/head'
import Feed from '../components/feed'
import Header from '../components/header'
import Modal from '../components/Modal'

export default function Home() {
  return (
    <div className='bg-gray-50 h-screen overflow-y-scroll scrollbar-hide'>
      <Head>
        <title>Poggersgram by Harry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    {/* Header */}
    <Header/>

    {/* feed */}
    <Feed/>

    {/* modal */}
    <Modal/>
        
    </div>
  )
}
